### ISSUE TITLE
Alphabetical ordering for the links?

### ISSUE THREAD

**Issue by marioortizmanero** [thibmaek/awesome-raspberry-pi#134]
- [x] My issue is an issue and not a PR. For additions or modifications I will create a [pull 
request](https://github.com/thibmaek/awesome-raspberry-pi/pulls).

How about alphabetically ordering all the links in this awesome list? Many others do it and it helps make the repository a bit less messy and easier to search.

**Comment by thibmaek** [comment]
Seems like a good idea.

**Comment by thibmaek** [comment]
Fixed in a152094473bbd3e23ff12c75e03ed09bc510dcc0
