### ISSUE TITLE
Some checks were failing while adding WebStation SYSMON to list

### ISSUE THREAD

**Issue by t0xic0der** [thibmaek/awesome-raspberry-pi#166]
- [X] My issue is an issue and not a PR. For additions or modifications I will create a [pull 
request](https://github.com/thibmaek/awesome-raspberry-pi/pulls).

Hi fellow contributors! I have added a repository of my tool to the list all while following the rules mentioned in the contributor guidelines - yet the CI throws an inexplicable error. Any help is appreciated.

**Comment by thibmaek** [comment]
Issue is not related to your change
