### ISSUE TITLE
Generated documentation has broken links to internal pages

### ISSUE THREAD

**Issue by koenvervloesem** [thibmaek/awesome-raspberry-pi#175]
- [X] My issue is an issue and not a PR. For additions or modifications I will create a [pull 
request](https://github.com/thibmaek/awesome-raspberry-pi/pulls).

I noticed you used absolute paths to other pages in some places:

```
README.md:Contribution guidelines can be found [here](/CONTRIBUTING.md)
```

And:

```
CONTRIBUTING.md:If you want you can add yourself to the [list of contributors](./CONTRIBUTORS.md).
```

This is [not officially supported by MkDocs](https://www.mkdocs.org/user-guide/writing-your-docs/).

The result is that these two links don't work on https://awesome-rpi.netlify.app/ but only if you visit the original Markdown pages on GitHub.

The Awesome Home Assistant project which you used as inspiration for your build script solves this by linking to the full URL on GitHub. But then visitors of the website will suddenly be forwarded to GitHub, which probably isn't what they expect.

Another solution is to just link to the relative paths `CONTRIBUTING.md` and `CONTRIBUTORS.md`, but then you encounter another issue: you created symlinks to these files with names in lower case, so the links won't work either. You can change the names of the symlinks to capital letters, but that's ugly. Or you can change the original filenames to lowercase letters and use these both on GitHub and in the generated website.

I'm not sure what the preferable solution is here.

**Comment by thibmaek** [comment]
Fixed in 4f3c01e49ac624061fc0f54999b968bbd0b17c87
