### ISSUE TITLE
pibakery is extinct, and so are it's downloads unless you build from github source.

### ISSUE THREAD

**Issue by Danrancan** [thibmaek/awesome-raspberry-pi#233]
- [ ] My issue is an issue and not a PR. For additions or modifications I will create a [pull 
request](https://github.com/thibmaek/awesome-raspberry-pi/pulls).

PiBakery has an author who is MIA, and doesn't seem to be active. All of his downloads (https://pibakery.org/docs/install-mac.html) on his website are broken links, and you can't find a download anywhere. Looks like the only way to get this is to build it from source using the github repository.

**Comment by thibmaek** [comment]
Removed in [44661e6](https://github.com/thibmaek/awesome-raspberry-pi/commit/44661e64e93bb33bcdd08fc09e83141baef3fb46)
