### ISSUE TITLE
new entry for the projects list

### ISSUE THREAD

**Issue by roccomuso** [thibmaek/awesome-raspberry-pi#46]
Add the Amazon Alexa project: https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi

**Comment by thibmaek** [comment]
I have a bunch of articles currently sitting in my Pocket queue to be added later on. If you want to see this added faster than I can get to it, please feel free to submit a PR using the provided guidelines :)

**Comment by thibmaek** [comment]
Closed by https://github.com/thibmaek/awesome-raspberry-pi/commit/c466c812ca08e8926dbe88afa1b922825bc19a65
