### ISSUE TITLE
Mega resource link from tech-knowhow.com

### ISSUE THREAD

**Issue by agsdot** [thibmaek/awesome-raspberry-pi#52]
- [x] My issue is an issue and not a PR. For additions or modifications I will create a [pull 
request](https://github.com/thibmaek/awesome-raspberry-pi/pulls).

@thibmaek , was researching more about the [chilipie-kiosk](https://github.com/futurice/chilipie-kiosk), discovered by virtue of your awesome list, and discovered this link - https://www.tech-knowhow.com/2017/01/raspberry-pi-disk-images-definitive-list .  

Just thought I'd share. Haven't cross referenced projects on that page vs your awesome list, but a good resource nonetheless.

Will close this issue in a few days, and maybe provide some PR's in the future based on it. But just thought I would share this resource.

**Comment by thibmaek** [comment]
Thanks for bringing it up. I was thinking about adding this list into my repository but it kind of defeats the purpose of having 2 lists that roughly do the same thing.

Where the other links are more topic-focused, adding this one in would feel like making the OS section obsolete. I'm also not sure this would conform to @sindresorhus' awesome manifesto.

Putting it on hold for a while, might revisit this later
