### ISSUE TITLE
Addition to the list: P4wnP1

### ISSUE THREAD

**Issue by careyer** [thibmaek/awesome-raspberry-pi#67]
Hi there,

you should definitely include the P4wnP1 project on your list - it is awesome:
https://github.com/mame82/P4wnP1

Cheers!

**Comment by thibmaek** [comment]
Hi @careyer 
Looks like a cool project indeed, please feel free to open a pull request which adds this item to the list.

If you're unsure how to contribute, start out by reading the [contribution guidelines](https://github.com/thibmaek/awesome-raspberry-pi/blob/master/CONTRIBUTING.md) and check out instructions for [making changes if your new to Github](https://github.com/thibmaek/awesome-raspberry-pi/blob/master/CONTRIBUTING.md#adding-an-item-to-the-list).

**Comment by thibmaek** [comment]
Closed in #74
