### ISSUE TITLE
Boards section

### ISSUE THREAD

**Issue by ikuamike** [thibmaek/awesome-raspberry-pi#89]
- [x] My issue is an issue and not a PR. For additions or modifications I will create a [pull 
request](https://github.com/thibmaek/awesome-raspberry-pi/pulls).
- Could you have a board section? Since there are several versions of the boards

**Comment by ikuamike** [comment]
I mean the raspberry pi versions of the board. Like raspberry 2, raspberry-pi 3, raspberry pi 3 b+, raspberry-pi zero and raspberry-pi zero w. Just a board section that mentions them

**Comment by ikuamike** [comment]
Shall I submit a PR? since you closed the issue?

**Comment by thibmaek** [comment]
Was closed in a commit :)

**Comment by ikuamike** [comment]
Awesome, just seen it :)
